version: '3'

services:
  db:
    image: postgres
    container_name: Database
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: test
    volumes:
      - /email_verify/database:/var/lib/mysql

  pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin_container
      restart: always
      environment:
        PGADMIN_CONFIG_WTF_CSRF_CHECK_DEFAULT: 'False'
        PGADMIN_CONFIG_WTF_CSRF_ENABLED: 'False'
        PGADMIN_DEFAULT_EMAIL: admin@gmail.com
        PGADMIN_DEFAULT_PASSWORD: admin
        PGADMIN_LISTEN_PORT: 5050
      ports:
        - "5050:5050"
      depends_on:
        - db

  